name: Deploy Pulumi Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Pulumi
        run: curl -fsSL https://get.pulumi.com | sh

      - name: Set Up AWS Credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

      - name: Set Up Pulumi Access Token
        run: echo "PULUMI_ACCESS_TOKEN=${{ secrets.PULUMI_ACCESS_TOKEN }}" >> $GITHUB_ENV

      - name: Install Dependencies
        run: npm install

      - name: Select Pulumi Stack
        run: pulumi stack select dev  # Replace "dev" with your actual stack name

      - name: Deploy with Pulumi
        run: pulumi up --yes
